quarkus.swagger-ui.always-include=true

# CloudEvent endpoint
# Defines the connector for the "kogito_incoming_stream" channel
mp.messaging.incoming.kogito_incoming_stream.connector=quarkus-http

# Defines the path for the "kogito_incoming_stream" channel's endpoint
mp.messaging.incoming.kogito_incoming_stream.path=/

#Persistence configuration
kogito.persistence.type=jdbc
kogito.persistence.optimistic.lock=true

# run create tables scripts
quarkus.flyway.migrate-at-start=true
quarkus.datasource.db-kind=postgresql


# Generate OpenAPIs with operationId
mp.openapi.extensions.smallrye.operationIdStrategy=METHOD

# OpenAPIs endpoint
quarkus.rest-client."supplier_yaml".url=http://localhost:8080


quarkus.rest-client."supplier_yaml".providers=services.CustomResponseExceptionMapper

microprofile.rest.client.disable.default.mapper=true


# Tracing
# quarkus.log.category."org.kie.kogito.event.impl".level=TRACE
# quarkus.log.min-level=TRACE

quarkus.smallrye-openapi.management.enabled=true

# quarkus.log.level=DEBUG
# OpenAPIs endpoint
quarkus.log.category."org.eclipse.microprofile.rest.client".level=DEBUG